// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV5aSFZPq5yBYU0iYz1PSuZh0zi4gNCUw',
    appId: '1:107345281388:web:dba94c1a294de9d9ddf349',
    messagingSenderId: '107345281388',
    projectId: 'financeanalyzer-7b302',
    authDomain: 'financeanalyzer-7b302.firebaseapp.com',
    storageBucket: 'financeanalyzer-7b302.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsorfr_y4i9AMZyzPhfkaC5A2SykRLx6g',
    appId: '1:107345281388:android:6be0c96f33b41ec7ddf349',
    messagingSenderId: '107345281388',
    projectId: 'financeanalyzer-7b302',
    storageBucket: 'financeanalyzer-7b302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWdp6mVXA0Etlccap95N1_5O5tLq45a1k',
    appId: '1:401420761874:ios:8492741deb1d847b45d1cb',
    messagingSenderId: '401420761874',
    projectId: 'financeanalyzer-f3700',
    storageBucket: 'financeanalyzer-f3700.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWdp6mVXA0Etlccap95N1_5O5tLq45a1k',
    appId: '1:401420761874:ios:8492741deb1d847b45d1cb',
    messagingSenderId: '401420761874',
    projectId: 'financeanalyzer-f3700',
    storageBucket: 'financeanalyzer-f3700.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvVthQ6mvh-63mzIkALfHqU2_nLT7z-yM',
    appId: '1:401420761874:web:e416da0c17459ff045d1cb',
    messagingSenderId: '401420761874',
    projectId: 'financeanalyzer-f3700',
    authDomain: 'financeanalyzer-f3700.firebaseapp.com',
    storageBucket: 'financeanalyzer-f3700.firebasestorage.app',
    measurementId: 'G-48JJY6C5TL',
  );

}